### ISSUE TITLE
Update issues templates

### ISSUE THREAD

**Issue by lengors** [ikari-engine/tensei-engine#4]
# Description

Update issues templates to use issue forms and prevent blank issues from being created.

# Tasks
- [x] Disable blank issues
- [x] Update bug report issue template 
- [x] Update feature request issue template
- [x] Create chore task issue template
